spring:
  redis:
      host: localhost
      password:
      port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///xblog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "020922"
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml